### ISSUE TITLE
Hoist `#!` attributes to before main

### ISSUE THREAD

**Issue by scottmcm** [panicbit/playbot_ng#17]
Right now it's annoying to use --nightly because `#![feature()]` doesn't work in the normal path:

```rust
fn main() {
    println!("{:?}", {
        #![feature(catch_expr)] let x: Option<_> = do catch { 4 }; x
    });
}


/* ~~~~=== stderr ===~~~~
   Compiling playground v0.0.1 (file:///playground)
error[E0658]: attributes on expressions are experimental. (see issue #15701)
 --> src/main.rs:3:9
  |
3 |         #![feature(catch_expr)] let x: Option<_> = do catch { 4 }; x
  |         ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(stmt_expr_attributes)] to the crate attributes to enable
```
https://play.rust-lang.org/?gist=43a13e12f5787eb3a814c09eed1db3fc&version=nightly&mode=debug

It would be nice for all `#!` attributes to just be moved up before main, like
```rust
#![feature(catch_expr)]

fn main() {
    println!("{:?}", {
        let x: Option<_> = do catch { 4 }; x
    });
}
```

Attributes are balanced in parens and such, so a slightly-hacky version of doing so is probably fine.  (Might even be "regex"able if you have crazy not-really-regex pcre or something.)

**Comment by panicbit** [comment]
For future reference: I went with the simple regex version that falls apart with nested brackets.
