### ISSUE TITLE
Eval disconnects on include_str! of Cargo.toml

### ISSUE THREAD

**Issue by Emerentius** [panicbit/playbot_ng#18]
Title says it all, basically.
```
<emerentius> eval: include_str!("../Cargo.toml")
* eval hat die Verbindung getrennt (RecvQ exceeded).
* eval (eval@moz-d2n.rie.25.85.IP) ist beigetreten.
```

I didn't try files outside of the crate. Eval is properly sandboxed, right?
Edit: Oh, it runs as root, too

**Comment by panicbit** [comment]
This was caused by eval trying too long of a message (the debug representation of the Cargo.toml is something over 4k bytes in a single line) and neither eval nor the irc crate truncating it.

Eval itself doesn't run the code; the playground does.
