### ISSUE TITLE
eval disappeared from #rust in mozilla irc

### ISSUE THREAD

**Issue by elichai** [panicbit/playbot_ng#43]
Hi,
eval Disappeared from #rust but it's still in #rust-beginners

**Comment by panicbit** [comment]
Odd, I'll fix it once I'm at home in about 3 hours. Sorry for the inconvenience :/

**Comment by panicbit** [comment]
Seems like my weechat client was unable to rejoin too. I'll probably have to add some rejoin logic to prevent issues like this in the future.

**Comment by panicbit** [comment]
eval is back :)
